### ISSUE TITLE
1.9 TODO

### ISSUE THREAD

**Issue by tterrag1098** [Chisel-Team/Chisel#80]
- [x] Fix resource reloads not reloading texture/face jsons
- [x] Add a way to infer multiple textures for types that need it
- [ ] 3D Chisel model
- [ ] Separate client and server code
- [x] Add R\* texture types
- [ ] Add blockpacks
- [ ] Internalize block factory
- [x] Add callback to access block object
- [x] Fix unloc name generation
- [x] Allow for Vanilla block model ovverides

**Comment by Drullkus** [comment]
@tterrag1098? ¯\_(ツ)_/¯
